### ISSUE TITLE
Differences in feature and UMI per cell counts between versions

### ISSUE THREAD

**Issue by pavsol** [10XGenomics/cellranger#129]
Hello,
I am reanalyzing the old scRNA-seq dataset. It was originally analyzed with Cell Ranger version 2.0.2. Now, I use version 6.0.1. I observe significant differences in the detected gene (nFeature_RNA) and UMI (nCounts_RNA) counts. Thus, I re-ran the analysis using both, 2.0.2 and 6.0.1 versions with the --force-cells parameter set to the same value to avoid the effect of different droplet filtration methods. I got the following output:

v2.0.2: nFeature_RNA median = 4418; nCounts_RNA median = 15141
v6.0.1: nFeature_RNA median = 1940; nCounts_RNA median = 3966

Since this difference is quite concerning, I would like to ask why does it happen and how it should be interpreted.

Thank you,
Pavel

**Comment by evolvedmicrobe** [comment]
Hello Pavsol,

That is a large difference, larger than we've typically seen between V2 and V3 (usually < 5%).

Between V2 and V3 Cell Ranger added some features to reduce the effect of data artifacts, such as PCR Chimeras, on UMI counts.  Although these artifacts tended to increase the perceived sensitivity of the assay, as they created additional UMIs, upon deeper inspection we discovered they were created in the PCR process and so should not be counted as observed UMIs on which scientific conclusions could be based.  Again, such artifacts were usually a small proportion of the total data, which is why your result is so surprising and unexpected.

It's likely worth digging into this more, as there may be aspects of you protocol (PCR cycles, clean-up steps, etc.) that are worth a look.  Please reach out to support@10xgenomics.com for more help on this issue.  If you can reference this GitHub issue and share data, we can provide you a higher level of support.

Warm wishes,
N
