### ISSUE TITLE
Missing XS attribute 

### ISSUE THREAD

**Issue by sridhar0605** [10XGenomics/cellranger#14]
Hello team, 

Wondering why strand information is missing from the bams aligned using Cellranger. I guess 
--outSAMstrandfield flag was missed in the alignment command, strand of each read pair is stored with XS attribute of the bam line. STAR does not include this in their alignments by default.

Any thoughts?

Thank you.

**Comment by pryvkin10x** [comment]
Our libraries are stranded (meaning that the genomic strand that a read aligned to is informative). The "senseness" or transcript strandedness is determined during the transcript alignment step, which we do ourselves after using STAR. We produce a TX tag containing the sense-transcript alignments and AN tag containing the antisense alignments.

https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam
(Note: The AN tag is currently undocumented due to an oversight - apologies for that)

As an aside, `--outSAMstrandfield` appears to be a feature that was added for compatibility with CuffLinks, and according to the STAR manual it infers the transcript strand from the intron motif strandedness. Thanks for pointing that out.

**Comment by sridhar0605** [comment]
thanks @pryvkin10x  for prompt response, 

Are TX and AN tags added to the bams by default by the cell ranger pipeline?

Thanks

**Comment by pryvkin10x** [comment]
Yes, that's correct.
