### ISSUE TITLE
cellranger-arc. error with  error] The peak caller called peak(s) spanning 98.24% of the genome. This could be caused by excessive background transposition or is a failure in peak calling

### ISSUE THREAD

**Issue by forrwill** [10XGenomics/cellranger#142]
I met the error of "error] The peak caller called peak(s) spanning 98.24% of the genome. This could be caused by excessive background transposition or is a failure in peak calling" when running cellranger-arc pipeline,  It seems that the peaks sum length is too long, Is there any parameters I can use to  filter the results.
![image](https://user-images.githubusercontent.com/41096851/140266596-8492409a-37e7-45c0-be5c-8d1c0f49db26.png)

**Comment by brettolsen** [comment]
Sure, the basic problem is that the peak caller is having a hard time finding peaks in the genome.   In this case, it is calling very very large peaks:  ~5000 total peaks that cover ~650million bp of the genome.

I can see that you are using an older version of cellranger-arc (because peakcaller_method is "standard", newer versions will be "revised").  I'd recommend updating to our latest version of cellranger-arc, released earlier this year.  This particular failure mode occasionally happened with the older versions when high levels of background transposition was present.  We have extensively revised the peak calling algorithm in the latest release to be much more robust to these kinds of library issues.

**Comment by forrwill** [comment]
> Sure, the basic problem is that the peak caller is having a hard time finding peaks in the genome. In this case, it is calling very very large peaks: ~5000 total peaks that cover ~650million bp of the genome.
> 
> I can see that you are using an older version of cellranger-arc (because peakcaller_method is "standard", newer versions will be "revised"). I'd recommend updating to our latest version of cellranger-arc, released earlier this year. This particular failure mode occasionally happened with the older versions when high levels of background transposition was present. We have extensively revised the peak calling algorithm in the latest release to be much more robust to these kinds of library issues.

thanks for your reply!, I have run the pipeline with cellranger-2.0, and completed successfully

**Comment by brettolsen** [comment]
Glad to hear it!  👍
