### ISSUE TITLE
1000-separating comma's inside outs/metrics_summary.csv 

### ISSUE THREAD

**Issue by plijnzaad** [10XGenomics/cellranger#145]
Dear 10X, 

the outs/metrics_summary.csv file contains comma's inside the double-quoted strings, e.g.
```
"3,728","104,967","1,809","391,320,145",97.9%,72.6%,96.0%,94.0%,95.8%,95.5%,85.4%,6.4%,26.4%,52.7%,49.2%,1.5%,88.2%,"23,098","6,510"
```

This makes it real pain to simply select simple characteristics like number of cells using shell tools such as `awk`. Could you please leave them out?

**Comment by evolvedmicrobe** [comment]
Hi @plijnzaad,

I really like this idea.  We originally formatted them that way because we had feedback from customers that they liked the numbers to appear as they did in the web summary, but I think your reaction might be more common.  We've started internal discussions on implementing this change.

Cheers,
Nigel

**Comment by plijnzaad** [comment]
Many thanks!

**Comment by plijnzaad** [comment]
PS: it would be very useful for Unix scripts if the keys (like "GEX Reads mapped confidently to transcriptome") don't contain spaces. Can't you replace them with underscores? Same is true for the input sample sheets, it would be very nice if underscores are silently converted to spaces (e.g. "Chromatin_Accessibility -> "Chromatin Accessibility")
