### ISSUE TITLE
Incorrect gex_umis_count and gex_genes_count reporting in per_barcode_metrics.csv file

### ISSUE THREAD

**Issue by kwcurrin** [10XGenomics/cellranger#165]
Hello,

I ran cellranger-arc v2.0.0 on several datasets. In the per_barcode_metrics.csv files, the gex_umis_count (column 20) and gex_genes_count (column 21) report 0 for every barcode. However, the sum of gex_exonic_umis and gex_intronic_umis (columns 14 and 18 respectively) have a wide range of values, ranging from 0 to over 100,000 as expected. 

Thanks,

Kevin

**Comment by evolvedmicrobe** [comment]
Hi Kevin,

Thanks for the ping on this, it was a known issue that was recently fixed in a Z-release of the software last february (see notes here: https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/release-notes), both columns should now show up correctly if you download and run the latest version.

Cheers,
Nigel

**Comment by kwcurrin** [comment]
Hi Nigel,

Thanks very much, and apologies for missing the release notes. 

Kevin
