### ISSUE TITLE
error in cellranger-atac mkref

### ISSUE THREAD

**Issue by rahulnutron** [10XGenomics/cellranger#226]
Dear Cellranger team,

I was trying to create a cellranger-atac reference for Arabidopsis. I used the genome and gtf files downloaded from igenome for Ensembl (Arabidopsis_thaliana_Ensembl_TAIR10). I used the same files before for cellranger count (not ATAC), that worked. However, here I am getting this error. I will be grateful for any suggestions.

Thanks for always being helpful,

Regards,
Rahul

configuration file

{
    organism: "Arabidopsis thaliana"
    genome: ["TAIR10"]
    input_fasta: ["/home/rahul/Downloads/Arabidopsis_thaliana_Ensembl_TAIR10/Arabidopsis_thaliana/Ensembl/TAIR10/Sequence/WholeGenomeFasta/genome.fa"]
    input_gtf: ["/home/rahul/Downloads/Arabidopsis_thaliana_Ensembl_TAIR10/Arabidopsis_thaliana/Ensembl/TAIR10/Annotation/Archives/archive-current/Genes/genes.gtf"]
    non_nuclear_contigs: ["Pt","Mt"]
    input_motifs: "/home/rahul/Downloads/JASPAR2022_CORE_plants_non-redundant_pfms_jaspar.pfm"
}

>>> Creating reference for TAIR10 <<<

Creating new reference folder at /media/rahul/New Volume/ATACARA/TAIR10
...done

Writing genome FASTA file into reference folder...
...done

Indexing genome FASTA file...
...done

Writing genes GTF file into reference folder...

mkref has FAILED
Error building reference package
Error while parsing GTF file /home/rahul/Downloads/Arabidopsis_thaliana_Ensembl_TAIR10/Arabidopsis_thaliana/Ensembl/TAIR10/Annotation/Archives/archive-current/Genes/genes.gtf
Supplied GTF is invalid. This row
['1', 'ensembl', 'exon', '3631', '3913', '.', '+', '.', 'exon_id "AT1G01010.1.exon1"; exon_number "1"; exon_version "1"; gene_biotype "protein_coding"; gene_id "AT1G01010"; gene_name "NAC001"; gene_source "ensembl"; gene_version "1"; p_id "P20332"; transcript_biotype "protein_coding"; transcript_id "AT1G01010.1"; transcript_name "ANAC001"; transcript_source "ensembl"; transcript_version "1"; tss_id "TSS22525";']
on line 2 specifies an 'exon' annotation for a transcript AT1G01010.1, but there is no 'transcript' row in the GTF for AT1G01010.1 that immediately precedes it.

Please fix your GTF and start again.

**Comment by shamer3** [comment]
I am having the exact same issue with the cellranger mkref pipeline, has there been any resolution found for this issue yet ?

**Comment by elehnert10x** [comment]
Thank you for your interest in Cell Ranger. GitHub Issues are not monitored by our support team. Please e-mail [support@10xgenomics.com](mailto:support@10xgenomics.com) for support with Cell Ranger or visit our documentation site at https://www.10xgenomics.com/support/software/cell-ranger.

**Comment by RayRay-23** [comment]
Hi, I encountered the same error, Could you please post the solution?

**Comment by IrinaVKuznetsova** [comment]
the same error

**Comment by katlande** [comment]
Hi all: [cellranger's mkref tutorial](https://www.10xgenomics.com/support/software/cell-ranger/latest/tutorials/cr-tutorial-mr) section **"Add a marker gene to the FASTA and GTF"** contains an error that causes this problem.

Their given instructions for how to make a transgenic gtf are incomplete, you need to add a 'gene' and 'transcript' line in addition to the exon line they provide. Specifically at this step of the tutorial:

`echo -e 'GFP\tunknown\texon\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' > GFP.gtf`

You would need to add two additional lines prior to this, instead running:
`echo -e 'GFP\tunknown\tgene\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' > GFP.gtf`
`echo -e 'GFP\tunknown\ttranscript\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' >> GFP.gtf`
`echo -e 'GFP\tunknown\texon\t1\t922\t.\t+\t.\tgene_id "GFP"; transcript_id "GFP"; gene_name "GFP"; gene_biotype "protein_coding";' >> GFP.gtf`

Here I am just using the same line of code but replacing 'exon' first with 'gene' and then with 'transcript'

IMPORTANTLY, once GFP.gtf already exists, make sure to use the double >> instead of a single > otherwise you will just overwrite GFP.gtf with each new line instead of adding a new line.
