### ISSUE TITLE
vdj with gamma delta libraries

### ISSUE THREAD

**Issue by sschattgen** [10XGenomics/cellranger#45]
Hi, 

I've generated libraries of TCR gamma and delta chains using the 5' chemistry and custom reverse primers. Cellranger vdj returns contigs with gamma/delta chains in the all_contig_annotations.csv output, however, the consensus_annotations.csv, clonotypes.csv, and vloupe files are not generated. I've noticed in the all_contig_annotations.csv file that all the TCRgd chains are called as "FALSE" under "is_cell" so I suspect these are being filtered during the annotation. Is there a potential workaround for gamma delta chains?

**Comment by crushseven-7** [comment]
Hi there,
I am planing on working on the  TCR gamma and delta chains library. Do you get any solution of this situation?

**Comment by sschattgen** [comment]
I had some success parsing the clonotypes using cell ranger v2.1.1 .

**Comment by aabarug** [comment]
For anyone delving into gamma delta VDJ data and looking for a solution - earlier this year in April, I had two VDJ datasets.  Cellranger 3.1.0 ran fine on the alpha beta TCR dataset but would automatically filter out gamma delta contigs for the second dataset. The advice I got from 10x was to run cellranger 3.0.2 to process the gamma-delta dataset. 

However, the version of 3.0.2 on the 10x website at the time had an bug (which had been fixed in later versions of cellranger) that 10x support had to email me a patch for to replace a script in my cellranger installation. Without the patch, 3.0.2 was run out of memory and crash anytime I tried to run it. I don't know if they've since updated the 3.0.2 that's sitting on the 10x software download page, so it might still have that bug.

In case 3.0.2 still has that bug, I can't attach the file as a python script so I've saved it as a [text file](https://github.com/10XGenomics/cellranger/files/5338350/__init__.txt) and attached it. It should be renamed as `__init__.py` and it should be inserted into and replace the file at this location in the cellranger 3.0.2 installation:
`cellranger-3.0.2/cellranger-cs/3.0.2/mro/stages/vdj/assemble_vdj/__init__.py`

Once that was done, I was able to run cellranger 3.0.2 on the gamma-delta TCR dataset successfully.
