### ISSUE TITLE
How the clonotypes are defined by cellranger vdj?

### ISSUE THREAD

**Issue by YiweiNiu** [10XGenomics/cellranger#51]
Hi,

I am using `cellranger vdj` to analyze the single cell vdj libraries.

But I am confused about the clonotype definition by the tool.

From [the documentation](https://support.10xgenomics.com/single-cell-vdj/software/pipelines/latest/algorithms/annotation), it says

> Cell barcodes are grouped together into clonotypes if they share the same set of productive CDR3 nucleotide sequences by exact match.

Does cellranger require that the CDR3 sequence of all the chains of IG or TR (e.g. IGH/IGK/IGL, TRA/TRB, TRD/TRG) are the samme or any one of these chains? If only the CDR3 match is only required by one of these chains, one cell may be assigned to different clonotypes.

I am new to this. Sorry if the question is too simple.

Thank you for your time.

Bests,
Yiwei

**Comment by WellJoea** [comment]
I have the same question, especially when use the results for other softwares, such as  vdjtools, immunarch.

**Comment by vadimnazarov** [comment]
Hello everyone, author of [immunarch](https://github.com/immunomind/immunarch) here. 

At the moment we group clonotypes by CDR3 nucleotide sequence+V gene+J gene+Chain. It means that sequences with same CDR3 nucleotide sequence+V gene+J gene in a same chain counted as a singular entity and their barcodes are merged together. I would love to hear more about it as this poses an important problem. Traditional RepSeq studies are heavily dependant on the definition of the clonotype due to diversity of statistics such as the number of public clonotypes, gene usage and others.
