### ISSUE TITLE
Fastq format???

### ISSUE THREAD

**Issue by yejg2017** [10XGenomics/cellranger#54]
When I run cellrange-arac count,and the fastqs' format in fastq path /Data/PCV-6  is :
PCV-6_S1_L001_I1_001.fastq.gz
PCV-6_S1_L001_I1_002.fastq.gz
PCV-6_S1_L001_I1_003.fastq.gz
PCV-6_S1_L001_I1_004.fastq.gz
PCV-6_S1_L001_I2_001.fastq.gz
PCV-6_S1_L001_I2_002.fastq.gz
PCV-6_S1_L001_I2_003.fastq.gz
PCV-6_S1_L001_I2_004.fastq.gz
PCV-6_S1_L001_R1_001.fastq.gz
PCV-6_S1_L001_R1_002.fastq.gz
PCV-6_S1_L001_R1_003.fastq.gz
PCV-6_S1_L001_R1_004.fastq.gz
PCV-6_S1_L001_R2_001.fastq.gz
PCV-6_S1_L001_R2_002.fastq.gz
PCV-6_S1_L001_R2_003.fastq.gz
PCV-6_S1_L001_R2_004.fastq.gz

Data
and I run the code ：
cellranger-atac count --id=PCV  --fastqs=/Data/PCV-6 --reference=refdata-cellranger-atac-GRCh38-1.2.0 --sample=PCV-6

But I always get the error: 
[error] Entry 0 in sample_defs are missing input FASTQs. I can not find the problem and how to fix it.Counld you help ye ,thanks!

**Comment by tdfy** [comment]
Hey yejg2017-- any luck with this? I'm having a similar problem.

**Comment by alirizaaribas-ibg** [comment]
<p>The pipeline couldn't start because the FASTQ directory is missing the R3 file. For <code>cellranger-atac count</code>, the I1 FASTQ is optional but the R1, R2, and R3 FASTQ files are all mandatory for the analysis.</p>
<p> </p>


RunInfo.xml | FASTQ name | Purpose | Length
-- | -- | -- | --
Read Number = "1" | R1 | Transposed DNA | 50
Read Number = "2" | I1 | Sample index (i7) | 8
Read Number = "3" | R2 | 10x barcode (i5) | 16
Read Number = "4" | R3 | Transposed DNA | 50


<p> </p>
<p>This error typically occurs when the BCL files are demultiplexed with <code>cellranger mkfastq</code> (which is designed for single cell gene expression data) instead of <code>cellranger-atac mkfastq</code> (which is used for single cell ATAC data). The solution is to re-demultiplex with the proper pipeline here: <a href="https://support.10xgenomics.com/single-cell-atac/software/downloads/latest" target="_self">Single Cell ATAC Software Downloads</a>.</p>The pipeline couldn't start because the FASTQ directory is missing the R3 file. For cellranger-atac count, the I1 FASTQ is optional but the R1, R2, and R3 FASTQ files are all mandatory for the analysis.

 
   RunInfo.xml    	   FASTQ name    	   Purpose    	   Length   
Read Number = "1" 	R1 	Transposed DNA 	50
Read Number = "2" 	I1 	Sample index (i7) 	8
Read Number = "3" 	R2 	10x barcode (i5) 	16
Read Number = "4" 	R3 	Transposed DNA 	50

 

This error typically occurs when the BCL files are demultiplexed with cellranger mkfastq (which is designed for single cell gene expression data) instead of cellranger-atac mkfastq (which is used for single cell ATAC data). The solution is to re-demultiplex with the proper pipeline here: [Single Cell ATAC Software Downloads](https://support.10xgenomics.com/single-cell-atac/software/downloads/latest).

https://kb.10xgenomics.com/hc/en-us/articles/360041540451--error-Entry-0-in-sample-defs-are-missing-input-FASTQs

Is it correct solution?
