### ISSUE TITLE
Reanalyze older BAM?

### ISSUE THREAD

**Issue by J-Moravec** [10XGenomics/cellranger#78]
Hi,
I have BAM file from the 10X `cellranger count` analysis and i would like to use it for GATK SNV pipeline. However, since this is an older experiment, I don't have the original reference genome available so I need to remap is again my transforming back to `fastq` and mapping it with a new reference genome.

This, however, wipes out all the sweet 10X BAM tags, such as the incredible important CB tag for distinguishing individual cells.

This brings me to my question: Is there a way to reanalyze older BAM files without access to the raw input from sequencer? I tried to look at the description of pipeline and even at the code, but its not as neatly described as I would like to. I know that STAR is involved and that there is `bamtofastq` https://github.com/10XGenomics/bamtofastq involved there, but can't figure out the order.

Thanks,
-- Jirka

**Comment by evolvedmicrobe** [comment]
Hi Jirka,

Indeed, `bamtofastq` is the tool for this job, since it takes a file with alignment information (the BAM) and produces one without it (FASTQ), you shouldn't need to worry about how STAR added in that alignment information.

Please contact: support@10xgenomics.com if you need any more help.

Cheers,
N
